(function(root){
  'use strict';
  const C=StudyCore,$=s=>document.querySelector(s),format=x=>x===null?'未定义':(x*100).toFixed(2)+'%';
  const examples=[{title:'只预测多数类',counts:{tp:0,fp:0,fn:10,tn:990}},{title:'找回8个正类',counts:{tp:8,fp:12,fn:2,tn:978}},{title:'完全正确的对照',counts:{tp:10,fp:0,fn:0,tn:990}}];
  let counts={...examples[0].counts},helpers,valid=true;
  function renderView({heading,panelHeader,h}){
    const cell=(key,label)=>`<td><label for="metric-${key}">${label}<input id="metric-${key}" type="number" min="0" max="1000000000" step="1" value="${counts[key]}" inputmode="numeric"></label></td>`;
    return heading('LOOK BEYOND ONE PERCENTAGE','99%准确率，也可能一个都没找到。','把真实类别放在行，预测类别放在列；先固定你关心的正类，再读指标。','<span class="pill blue">二分类 · 计数可核对</span>')+`<div class="metrics-layout"><section class="panel">${panelHeader('先看四格发生了什么','这里的默认值是自编示例，不是digits模型测试结果。')}<div class="panel-body"><div class="examples">${examples.map((e,i)=>`<button class="example-button" data-action="metric-example" data-index="${i}">${h(e.title)}</button>`).join('')}</div><table class="metric-matrix"><thead><tr><th scope="col">真实 / 预测</th><th scope="col">预测正类</th><th scope="col">预测负类</th></tr></thead><tbody><tr><th scope="row">真实正类</th>${cell('tp','命中 TP')}${cell('fn','漏检 FN')}</tr><tr><th scope="row">真实负类</th>${cell('fp','误报 FP')}${cell('tn','排除 TN')}</tr></tbody></table><p id="metric-error" class="form-error" role="alert"></p><div id="metric-summary"></div><div class="data-buttons"><button class="button primary" data-action="metric-export">导出指标记录</button><button class="button" data-action="metric-card">存为回忆卡</button></div><p class="source-note">每格0–10亿整数；输入有效时自动计算。实验仅在页面中保留，刷新会重置。</p></div></section><section class="panel">${panelHeader('每个指标，到底除以什么？','百分比保留2位小数，分子与分母可直接复核。')}<div class="panel-body"><div id="metric-results" class="metric-results"></div><div id="metric-insight" class="notes-callout"></div></div></section></div><div class="data-grid section-gap"><section class="panel">${panelHeader('同样1000个样本，怎样比较？')}<div class="panel-body"><p>默认示例真实正类只有10个。全部预测负类会得到99%准确率，但10个正类全部漏掉。</p><p class="section-gap">第二个示例找回8个正类，另外误报12个负类。准确率变为98.6%，正类Recall为80%，Precision为40%。这些指标回答不同问题，不能单凭准确率决定实际方案。</p><p class="source-note">真实应用还要固定目标类、评估数据和错误代价；这里仅展示自编计数的数学关系。</p></div></section><section class="panel">${panelHeader('空分母与使用约定')}<div class="panel-body"><ul class="checklist"><li>没有预测正类时，Precision分母为0，显示未定义。</li><li>没有真实正类时，Recall未定义；没有真实负类时，特异度未定义。</li><li>F1直接计算2TP / (2TP+FP+FN)，不会强行从两个已格式化的百分比反算。</li><li>本实验平衡准确率取正、负两类Recall的平均；任一类缺失时显示未定义。</li></ul><p class="source-note">不同软件可约定零除时返回0、1或NaN，比较报告前应核对约定。公式依据：<a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html" target="_blank" rel="noopener noreferrer">scikit-learn指标文档</a>。</p></div></section></div>`;
  }
  function update(){
    try{
      const next=Object.fromEntries(['tp','fp','fn','tn'].map(k=>[k,$('#metric-'+k).value.trim()===''?NaN:Number($('#metric-'+k).value)])),m=C.classificationMetrics(next);counts=next;valid=true;$('#metric-error').textContent='';
      const rows=[['accuracy','Accuracy · 所有样本',`${counts.tp+counts.tn} / ${m.total}`],['precision','Precision · 预测正类',`${counts.tp} / ${m.predictedPositive}`],['recall','Recall · 真实正类',`${counts.tp} / ${m.actualPositive}`],['f1','F1 · 正类',`${2*counts.tp} / ${2*counts.tp+counts.fp+counts.fn}`],['specificity','特异度 · 真实负类',`${counts.tn} / ${m.actualNegative}`],['balancedAccuracy','平衡准确率','(正类Recall + 负类Recall) / 2']];
      $('#metric-results').innerHTML=rows.map(([key,title,fraction])=>`<div class="metric-value"><span>${title}</span><strong data-metric="${key}">${format(m[key])}</strong><small>${fraction}</small></div>`).join('');
      $('#metric-summary').innerHTML=`<div class="notice-box"><strong>样本 ${m.total.toLocaleString('zh-CN')} · 真实正类 ${m.actualPositive.toLocaleString('zh-CN')}</strong><p>正类占比 ${format(m.prevalence)}；固定预测多数类的准确率基线 ${format(m.majorityBaseline)}。</p></div>`;
      let insight=m.total===0?'当前没有样本。所有指标均未定义，不能把空结果当作0%或100%。':m.actualPositive===0?'当前没有真实正类，无法据此观察正类Recall；这份数据没有检验正类能力。':m.actualNegative===0?'当前没有真实负类，无法据此观察负类能力；本实验平衡准确率也未定义。':m.predictedPositive===0?`当前一个正类都没预测。准确率 ${format(m.accuracy)}，但正类Recall为0%；Precision未定义，F1按计数公式为0。`:`共命中${counts.tp}个正类，漏检${counts.fn}个，误报${counts.fp}个。Precision看预测为正的样本中有多少真实正类，Recall看找回了多少真实正类。`;
      $('#metric-insight').textContent=insight;
    }catch(error){valid=false;$('#metric-error').textContent=error.message;$('#metric-summary').innerHTML='';$('#metric-results').innerHTML='<p class="muted">等待四格有效输入。</p>';$('#metric-insight').textContent='修正输入后再查看指标，避免把上次结果当成当前计算。';}
    for(const el of document.querySelectorAll('[data-action="metric-export"],[data-action="metric-card"]'))el.disabled=!valid;
  }
  function mount(){for(const key of ['tp','fp','fn','tn'])$('#metric-'+key).addEventListener('input',update);update();}
  function record(){const m=C.classificationMetrics(counts);return ['# 二分类指标实验记录','','自编计数 / 自填计数；正类定义应由记录者补充。','',`TP=${counts.tp}, FP=${counts.fp}, FN=${counts.fn}, TN=${counts.tn}`,`真实正类=${m.actualPositive}，真实负类=${m.actualNegative}，总数=${m.total}`,'',...Object.entries({Accuracy:m.accuracy,Precision:m.precision,Recall:m.recall,F1:m.f1,Specificity:m.specificity,BalancedAccuracy:m.balancedAccuracy}).map(([k,v])=>`${k}: ${format(v)}`),'','零分母显示未定义；F1按2TP/(2TP+FP+FN)直接计算。平衡准确率要求真实正负类均存在。','', '正类定义：','要回答的问题：','哪些错误代价更高：','目前不能得出的结论：'].join('\n');}
  function actions(deps){helpers=deps;return{
    'metric-example':el=>{counts={...examples[Number(el.dataset.index)].counts};helpers.render();},
    'metric-export':()=>{if(valid)helpers.showText('二分类指标记录',record(),'二分类指标记录.md');},
    'metric-card':()=>{if(valid)helpers.addCard({question:'为什么99%的准确率可能仍然完全漏掉目标类？Precision和Recall各自除以什么？',answer:record()+'\n\n先固定正类；Precision=TP/(TP+FP)，Recall=TP/(TP+FN)。类别比例失衡时应结合这些分母与实际错误分析，不能只看Accuracy。'});}
  };}
  root.StudyMetrics={renderView,mount,actions};
})(globalThis);
