(function(root){
  'use strict';
  const V=StudyVault;let ctx,records=[],files=[],editing=null,query='',year='',urls=[];
  const h=x=>ctx.h(x),categories=['学习','竞赛','学生工作','体育','志愿服务','科研','其他'];
  function renderView(helpers){ctx=helpers;return ctx.heading('KEEP THE EVIDENCE','综测记录台','把活动、获奖和证明放在一起，申报时按学年检索。', '<button class="button primary" id="record-add">记录活动</button>')+'<div id="records-root"><p>正在打开本地记录…</p></div>';}
  async function mount(){const el=document.querySelector('#records-root');try{await V.migrate(ctx.getLegacy().experiences);[records,files]=await Promise.all([V.all('records'),V.all('files')]);if(!el?.isConnected)return;paint(el);document.querySelector('#record-add').onclick=()=>openForm();}catch(e){if(el?.isConnected)el.textContent=e.message;}}
  const selectedRecords=()=>records.filter(r=>(!query||[r.title,r.organizer,r.award,r.notes,r.category].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!year||r.date.startsWith(year))).sort((a,b)=>b.date.localeCompare(a.date));
  function paint(el){for(const url of urls)URL.revokeObjectURL(url);urls=[];const years=[...new Set(records.map(r=>r.date.slice(0,4)).filter(Boolean))].sort().reverse();el.innerHTML=`<div class="record-stats"><div><strong>${records.length}</strong><span>活动记录</span></div><div><strong>${records.filter(r=>r.fileIds.length).length}</strong><span>已附证明</span></div><div><strong>${files.filter(f=>records.some(r=>r.id===f.owner)).length}</strong><span>证明文件</span></div></div><section class="panel"><div class="panel-body"><div class="record-filters"><label>搜索活动 / 单位 / 奖项<input id="record-query" type="search" value="${h(query)}" placeholder="例如：志愿服务、数学建模"></label><label>年份<select id="record-year"><option value="">所有年份</option>${years.map(y=>`<option ${year===y?'selected':''}>${h(y)}</option>`).join('')}</select></label><button class="button" id="record-csv">导出当前列表 CSV</button><button class="button" id="record-backup">完整备份（含证明）</button></div><p class="source-note">记录活动事实，不自动判定分值。旧经历已迁移，未知举办单位、奖级和时间留空待补。</p><div id="record-list"></div></div></section><details class="panel legacy-draft"><summary>保留的旧申请草稿</summary><div class="panel-body"><p class="preserve-lines">${h(ctx.getLegacy().drafts||'没有旧草稿。')}</p><button class="button" id="record-draft-export">下载旧草稿</button></div></details><dialog id="record-dialog" aria-labelledby="record-heading"><form id="record-form"><div class="dialog-heading"><h2 id="record-heading">记录活动</h2><button type="button" class="icon-button" id="record-close" aria-label="关闭">×</button></div><label>活动名称<input name="title" maxlength="300" required placeholder="填写活动或比赛全称"></label><label>举办单位<input name="organizer" maxlength="300" required placeholder="例如：学院、学校、学会"></label><div class="form-row"><label>获奖等级<input name="award" maxlength="200" required placeholder="例如：校级一等奖 / 未获奖（参与）"></label><label>活动 / 获奖日期<input name="date" type="date" required></label></div><label>分类<select name="category">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label><label>个人贡献 / 备注<textarea name="notes" rows="3" maxlength="6000"></textarea></label><label>添加证明材料（支持多选）<input id="record-files" type="file" multiple></label><p class="hint">可保存照片、PDF、Word、压缩包等文件。每份最大20 MB，每项最多10份。文件只保存在本浏览器；非照片文件以下载方式查看。</p><div id="record-current-files"></div><p id="record-error" class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" class="button" id="record-cancel">取消</button><button class="button primary" id="record-save">保存活动与证明</button></div></form></dialog>`;
    el.querySelector('#record-query').oninput=e=>{query=e.target.value;paintList(el);};el.querySelector('#record-year').onchange=e=>{year=e.target.value;paintList(el);};el.querySelector('#record-csv').onclick=()=>exportCSV();el.querySelector('#record-backup').onclick=()=>ctx.fullBackup();el.querySelector('#record-draft-export').onclick=()=>V.download(new Blob([ctx.getLegacy().drafts],{type:'text/plain;charset=utf-8'}),'原申请草稿.txt');
    for(const key of ['record-close','record-cancel'])el.querySelector('#'+key).onclick=()=>el.querySelector('#record-dialog').close();
    el.querySelector('#record-form').onsubmit=async e=>{e.preventDefault();const form=e.target,save=el.querySelector('#record-save'),error=el.querySelector('#record-error');save.disabled=true;error.textContent='';try{const values=Object.fromEntries(new FormData(form));if(!values.title.trim()||!values.organizer.trim()||!values.award.trim()||!values.date)throw new Error('请完整填写活动、举办单位、获奖等级和日期。');const prior=records.find(r=>r.id===editing),remove=[...form.querySelectorAll('[data-remove-file]:checked')].map(e=>e.value),record={id:editing||V.id(),title:values.title.trim(),organizer:values.organizer.trim(),award:values.award.trim(),date:values.date,category:values.category,notes:values.notes.trim(),fileIds:prior?.fileIds||[]};const newFiles=[...el.querySelector('#record-files').files];if(record.fileIds.length-remove.length+newFiles.length>10)throw new Error('每项活动最多10份证明材料。');if(!StudyCore.validDate(record.date))throw new Error('日期无效。');await V.saveRecord(record,newFiles,remove);el.querySelector('#record-dialog').close();ctx.toast('活动和证明已保存到本地。');await mount();}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};
    el.querySelector('#record-list').onclick=async e=>{const btn=e.target.closest('[data-record]');if(!btn)return;try{if(btn.dataset.record==='edit')openForm(records.find(r=>r.id===btn.dataset.id));if(btn.dataset.record==='file')await V.openFile(btn.dataset.id);if(btn.dataset.record==='delete'&&confirm('删除此活动和它的证明材料？请先导出完整备份。')){await V.deleteOwner('records',btn.dataset.id);await mount();ctx.toast('活动及证明已删除。');}}catch(error){ctx.toast(error.message);}};
    paintList(el);
  }
  function paintList(el){for(const url of urls)URL.revokeObjectURL(url);urls=[];const list=selectedRecords();el.querySelector('#record-list').innerHTML=list.length?list.map(r=>`<article class="record-card"><div class="record-card-heading"><div><span class="pill">${h(r.category)}</span><h3>${h(r.title)}</h3><p>${h(r.organizer||'举办单位待补充')} · ${h(r.date||'日期待补充')}</p></div><strong class="award-badge">${h(r.award||'奖级待补充')}</strong></div>${r.notes?`<p class="preserve-lines">${h(r.notes)}</p>`:''}<div class="evidence-grid">${r.fileIds.map(key=>{const f=files.find(x=>x.id===key);if(!f)return '<p>证明缺失，请恢复备份。</p>';let image='';if(['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)){const url=URL.createObjectURL(f.blob);urls.push(url);image=`<img src="${url}" alt="${h(f.name)}" loading="lazy" width="160" height="100">`;}return `<button class="evidence-file" data-record="file" data-id="${h(key)}">${image||'<span class="evidence-icon" aria-hidden="true">▤</span>'}<span>${h(f.name)}</span><small>${(f.blob.size/1024).toFixed(1)} KB · 下载</small></button>`;}).join('')||'<p class="muted">还没有证明附件。</p>'}</div><div class="data-buttons"><button class="button" data-record="edit" data-id="${h(r.id)}">编辑与补充证明</button><button class="button ghost" data-record="delete" data-id="${h(r.id)}">删除活动</button></div></article>`).join(''):'<div class="empty"><h3>暂无匹配的活动记录</h3><p>活动结束后记下名称、举办单位、奖级和日期，再附上证明文件。</p></div>';}
  function openForm(record=null){const form=document.querySelector('#record-form');if(!form)return;form.reset();editing=record?.id||null;if(record)for(const key of ['title','organizer','award','date','category','notes'])form.elements[key].value=record[key];document.querySelector('#record-heading').textContent=record?'编辑活动与证明':'记录活动';document.querySelector('#record-error').textContent='';document.querySelector('#record-current-files').innerHTML=(record?.fileIds||[]).map(key=>`<label class="remove-file"><input type="checkbox" data-remove-file value="${h(key)}">移除：${h(files.find(f=>f.id===key)?.name||'缺失附件')}</label>`).join('');document.querySelector('#record-dialog').showModal();}
  function exportCSV(){const safe=x=>{let value=String(x);if(/^[=+\-@\t\r]/.test(value))value="'"+value;return '"'+value.replace(/"/g,'""')+'"';};const rows=[['活动名称','举办单位','获奖等级','日期','分类','备注','证明文件'],...selectedRecords().map(r=>[r.title,r.organizer,r.award,r.date,r.category,r.notes,r.fileIds.map(k=>files.find(f=>f.id===k)?.name||'缺失').join('；')])];V.download(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'综测活动记录.csv');}
  root.StudyRecords={renderView,mount,openForm};
})(globalThis);
