(function(root){
  'use strict';
  let run=StudyTrainingRun,stage='pretrain',ctx;
  const stages=[['pretrain','预训练'],['sft','监督微调'],['lora','LoRA微调'],['dpo','DPO偏好优化']];
  function validate(input){if(!input||typeof input!=='object'||typeof input.description!=='string'||input.description.length>2000||!input.stages||!input.evaluation)throw new Error('请选择完整的训练报告JSON。');for(const [id] of stages){const s=input.stages[id],e=input.evaluation[id];if(!s||s.stage!==id||!Array.isArray(s.history)||!s.history.length||s.history.length>10000||!Number.isSafeInteger(s.trainableParameters)||s.trainableParameters<1||s.trainableParameters>1e12||!Number.isSafeInteger(s.totalParameters)||s.totalParameters<s.trainableParameters||s.totalParameters>1e12||typeof s.device!=='string'||s.device.length>100||s.history.some(r=>!r||!Number.isInteger(r.step)||r.step<1||!Number.isFinite(r.loss)||r.loss<0||r.loss>1e6)||!e||!Number.isFinite(e.validation?.loss)||e.validation.loss<0||!Number.isFinite(e.test?.loss)||e.test.loss<0)throw new Error('训练阶段或评估指标无效。');}return input;}
  function renderView(helpers){ctx=helpers;return '<section class="panel"><div class="panel-body" id="training-lab"></div></section>';}
  function mount(){const el=document.querySelector('#training-lab');if(!el)return;paint(el);}
  function chart(history){const width=600,height=220,left=50,top=16,right=20,bottom=35,values=history.map(r=>r.loss),max=Math.max(...values,.01)*1.1,steps=Math.max(...history.map(r=>r.step),1),x=step=>left+(width-left-right)*step/steps,y=value=>top+(height-top-bottom)*(1-value/max);return `<svg class="training-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="所选阶段实际训练loss轨迹"><line x1="${left}" x2="${width-right}" y1="${height-bottom}" y2="${height-bottom}" stroke="#9ba8bc"/><line x1="${left}" x2="${left}" y1="${top}" y2="${height-bottom}" stroke="#9ba8bc"/>${[0,.5,1].map(f=>`<text x="${left-8}" y="${y(f*max)+4}" text-anchor="end" fill="#65738c" font-size="12">${(f*max).toFixed(2)}</text>`).join('')}<polyline fill="none" stroke="#2563eb" stroke-width="3" points="${history.map(r=>`${x(r.step)},${y(r.loss)}`).join(' ')}"/><text x="${left}" y="${height-9}" fill="#65738c" font-size="12">0 step</text><text x="${width-right}" y="${height-9}" text-anchor="end" fill="#65738c" font-size="12">${steps} step</text></svg>`;}
  function paint(el){const h=ctx.h,s=run.stages[stage],e=run.evaluation[stage];el.innerHTML=`<h2>真实小型Decoder训练记录</h2><p>${h(run.description)}</p><div class="segmented training-modes">${stages.map(([id,title])=>`<button data-train-stage="${id}" class="${id===stage?'active':''}" aria-pressed="${id===stage}">${title}</button>`).join('')}</div><div class="record-stats"><div><strong>${s.totalParameters.toLocaleString()}</strong><span>总参数</span></div><div><strong>${s.trainableParameters.toLocaleString()}</strong><span>本阶段可训练参数</span></div><div><strong>${s.history.at(-1).step}</strong><span>实际更新步数</span></div></div><p class="source-note">计算设备：${h(s.device)}。图表为本阶段记录的训练目标；预训练全token，SFT/LoRA仅响应，DPO为偏好目标，各阶段loss不可混比。</p>${chart(s.history)}<div class="table-scroll"><table class="data-table"><thead><tr><th>同一响应mask下评估</th><th>平均loss</th><th>PPL</th><th>有效token</th><th>未知输入token</th></tr></thead><tbody>${['validation','test'].map(key=>`<tr><th>${key==='validation'?'验证集':'测试集'}</th><td>${e[key].loss.toFixed(5)}</td><td>${Number(e[key].perplexity).toFixed(3)}</td><td>${Number(e[key].tokens)}</td><td>${Number(e[key].unknownInputTokens)}</td></tr>`).join('')}</tbody></table></div>${stage==='lora'?`<p class="notes-callout">冻结基座检查：${s.frozenBaseUnchanged?'权重逐张量完全一致':'此报告未确认'}；这里只更新qkv/proj低秩适配器。</p>`:''}${stage==='dpo'?'<p class="notes-callout">DPO起点策略等于参考，首个loss约0.693。该教学数据上的测试loss可能退化；偏好目标改善不能当作通用能力提升。</p>':''}<details><summary>逐步训练日志</summary><div class="table-scroll"><table class="data-table"><thead><tr><th>step</th><th>loss</th><th>梯度范数</th><th>学习率</th></tr></thead><tbody>${s.history.map(r=>`<tr><td>${r.step}</td><td>${r.loss.toFixed(6)}</td><td>${Number(r.gradNorm).toFixed(4)}</td><td>${Number(r.lr)}</td></tr>`).join('')}</tbody></table></div></details><label>读取自己的汇总报告<input type="file" id="training-report" accept=".json,application/json"></label><p class="hint">执行tiny_llm.py all后生成training-report.json。最大10 MB；本地读取，不发送到API。刷新恢复内置实测示例。</p><p id="training-error" role="alert"></p><button class="button" id="training-reset">查看内置CPU实测</button>`;
    el.onclick=e=>{const choice=e.target.closest('[data-train-stage]');if(choice){stage=choice.dataset.trainStage;paint(el);}if(e.target.id==='training-reset'){run=StudyTrainingRun;paint(el);}};
    el.querySelector('#training-report').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw new Error('训练报告最大10 MB。');run=validate(JSON.parse(await file.text()));paint(el);}catch(error){el.querySelector('#training-error').textContent=error.message;}};
  }
  root.StudyTrainingLab={renderView,mount,validate};
})(globalThis);
