'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('./browser-runtime.cjs').playwright;
const base=process.env.STUDY_URL||'http://127.0.0.1:5179';
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||undefined});
  try{const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
  await page.goto(base+'/#logic');await page.locator('#book-upload').waitFor();
  await page.locator('#book-upload').setInputFiles(path.resolve('output/pdf/数字逻辑与AI基础速练册.pdf'));
  await page.waitForFunction(()=>document.querySelector('#book-message')?.textContent.includes('PDF已保存'),{timeout:30000});
  const book=await page.evaluate(async()=> (await StudyVault.all('books'))[0]);assert.equal(book.pages.length,7);assert(book.pages.some(p=>p.text.includes('卡诺')));
  await page.locator('[data-book=outline]').click();assert.match(await page.locator('#book-message').textContent(),/填写/);
  let calls=0;
  await page.route('**/api/textbook',async route=>{calls++;const payload=route.request().postDataJSON();assert.equal(payload.key,'test-only-placeholder');const content=payload.kind==='outline'?{title:'测试教材',sections:[{title:'教材主题',start:1,end:2,summary:'依据导入教材'}]}:{title:'教材学习展示',summary:'模拟API协议验收，不是实际DeepSeek产物',concepts:[{title:'卡诺图分组',text:'四角可按首尾相邻合并。<img src=x onerror=alert(1)>',pages:[1]}],steps:[{title:'核对覆盖',text:'检查每个1都被覆盖。',pages:[2]}],comparisons:[{title:'对照',columns:['类型','含义'],rows:[['1','必须覆盖']],pages:[1]}],charts:[{title:'教材页数示例（模拟）',labels:['a','b'],values:[1,-2],unit:'',pages:[1]}],questions:[{question:'为什么核对原文？',answer:'生成内容可能有误。',pages:[1]}]};await route.fulfill({json:{content,usage:{promptTokens:100,completionTokens:20}}});});
  assert.equal(await page.locator('#book-base-url').inputValue(),'https://api.deepseek.com');
  await page.locator('#book-base-url').fill('https://ai.example.org/campus/v1/');await page.locator('#book-model').fill('school/Qwen:instruct');
  await page.route('**/api/textbook',async(route)=>{const payload=route.request().postDataJSON();assert.equal(payload.baseUrl,'https://ai.example.org/campus/v1/');assert.equal(payload.model,'school/Qwen:instruct');await route.fallback();});
  await page.locator('#book-key').fill('test-only-placeholder');await page.locator('[data-book=outline]').click();await page.waitForFunction(()=>document.querySelector('#book-message')?.textContent.includes('已生成并保存'));assert.equal(await page.locator('#book-base-url').inputValue(),'https://ai.example.org/campus/v1/');
  await page.locator('#book-range').selectOption('1-2');await page.locator('[data-book=generate]').click();await page.locator('.book-lesson').waitFor();assert.equal(calls,2);assert.equal(await page.locator('#book-display img').count(),0);assert(await page.locator('#book-display').textContent().then(x=>x.includes('<img')));
  await page.reload();await page.locator('#book-key').waitFor();assert.equal(await page.locator('#book-key').inputValue(),'');assert.equal(await page.locator('#book-base-url').inputValue(),'https://api.deepseek.com');await page.locator('#book-range').selectOption('1-2');await page.locator('.book-lesson').waitFor();
  const beforeCancel=await page.evaluate(async()=>JSON.stringify((await StudyVault.all('books'))[0].lessons));
  let releaseSlow;const slowGate=new Promise(resolve=>releaseSlow=resolve);
  const slowRoute=async route=>{await slowGate;await route.abort().catch(()=>{});};
  await page.route('**/api/textbook',slowRoute);await page.locator('#book-key').fill('test-only-placeholder');await page.locator('[data-book=generate]').click();await page.locator('[data-book=cancel]').waitFor();assert.match(await page.locator('#book-message').textContent(),/不自动超时取消/);
  await page.locator('[data-book=cancel]').click();await page.waitForFunction(()=>document.querySelector('#book-message')?.textContent.includes('生成已取消'));releaseSlow();await page.unroute('**/api/textbook',slowRoute);
  assert.equal(await page.evaluate(async()=>JSON.stringify((await StudyVault.all('books'))[0].lessons)),beforeCancel);
  await page.goto(base+'/#ai');await page.locator('#course-notes').waitFor();assert.equal(await page.locator('.course-stage').count(),8);assert((await page.locator('[data-lesson]').count())>=39);await page.locator('#course-notes').fill('实际完成形状检查');await page.locator('#course-complete').click();await page.waitForFunction(()=>document.querySelector('#course-complete')?.textContent.includes('取消'));
  await page.reload();await page.locator('#course-notes').waitFor();assert.equal(await page.locator('#course-notes').inputValue(),'实际完成形状检查');
  await page.locator('[data-lesson=attention]').first().click();await page.locator('#course-lab').click();await page.locator('#attention-result').waitFor();assert.match(await page.locator('#attention-result').textContent(),/1\.00000/);await page.locator('#attention-causal').uncheck();await page.locator('#attention-calc').click();assert.equal(await page.locator('#attention-result td').count(),12);
  await page.locator('[data-lesson=linear]').first().click();await page.locator('#course-lab').click();await page.locator('[data-action=ai-step]').click();await page.locator('#ai-train').waitFor({state:'attached'});
  await page.locator('[data-lesson=project]').first().click();await page.locator('#course-lab').click();await page.locator('#training-lab').waitFor();assert.match(await page.locator('#training-lab').textContent(),/107,804/);await page.locator('[data-train-stage=lora]').click();assert.match(await page.locator('#training-lab').textContent(),/3,072/);await page.locator('[data-train-stage=dpo]').click();assert.match(await page.locator('#training-lab').textContent(),/退化/);await page.goto(base+'/#materials');await page.locator('#record-add').click();await page.locator('#record-form').waitFor();
  await page.locator('#record-form [name=title]').fill('=测试活动 <script>danger()</script>');await page.locator('#record-form [name=organizer]').fill('测试举办单位');await page.locator('#record-form [name=award]').fill('校级一等奖');await page.locator('#record-form [name=date]').fill('2026-10-02');await page.locator('#record-form [name=notes]').fill('模拟数据，仅用于附件字节验收。');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDAAAAAASUVORK5CYII=','base64'),proof=Buffer.from([0,1,2,127,128,255]);
  await page.locator('#record-files').setInputFiles([{name:'证明照片.png',mimeType:'image/png',buffer:png},{name:'证明文件.bin',mimeType:'application/octet-stream',buffer:proof}]);await page.locator('#record-save').click();await page.locator('.record-card').waitFor();assert.equal(await page.locator('.evidence-file').count(),2);assert.equal(await page.locator('.record-card script').count(),0);
  await page.reload();await page.locator('.record-card').waitFor();assert.match(await page.locator('.record-card').textContent(),/测试举办单位/);
  await page.locator('[data-record=edit]').click();await page.locator('#record-form [name=award]').fill('校级二等奖');await page.locator('#record-save').click();await page.waitForFunction(()=>document.querySelector('.award-badge')?.textContent==='校级二等奖');assert.equal(await page.locator('.evidence-file').count(),2);
  let promise=page.waitForEvent('download');await page.locator('#record-csv').click();let downloaded=await promise;assert((await fs.promises.readFile(await downloaded.path(),'utf8')).includes("'=测试活动"));
  promise=page.waitForEvent('download');await page.locator('#record-backup').click();downloaded=await promise;const backupPath=await downloaded.path(),backup=JSON.parse(await fs.promises.readFile(backupPath,'utf8'));assert.equal(backup.records.length,1);assert.equal(backup.books.length,1);assert(!JSON.stringify(backup).includes('test-only-placeholder'));assert(Buffer.from(backup.files.find(f=>f.name==='证明文件.bin').data,'base64').equals(proof));
  // Invalid restore never changes persisted data.
  assert(!JSON.stringify(backup).includes('https://ai.example.org/campus/v1/'));assert(!JSON.stringify(backup).includes('school/Qwen:instruct'));
  assert(await page.evaluate(async input=>{input.files[0].size++;try{StudyVault.validateBackup(input);return false;}catch{return (await StudyVault.all('records')).length===1;}},structuredClone(backup)));
  await page.locator('[data-record=delete]').click();await page.waitForFunction(async()=> (await StudyVault.all('records')).length===0);
  await page.goto(base+'/#data');await page.locator('#full-import-file').setInputFiles({name:'完整备份.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-action').click();await page.waitForFunction(async()=> (await StudyVault.all('records')).length===1);await page.goto(base+'/#materials');await page.locator('.record-card').waitFor();assert.equal(await page.locator('.evidence-file').count(),2);
  const restored=await page.evaluate(async()=>{const f=(await StudyVault.all('files')).find(x=>x.name==='证明文件.bin');return [...new Uint8Array(await f.blob.arrayBuffer())];});assert.deepEqual(restored,[...proof]);
  fs.mkdirSync('docs/screenshots-v2',{recursive:true});
  for(const route of ['logic','ai','materials']){await page.goto(base+'/#'+route);await page.locator(route==='logic'?'#book-upload':route==='ai'?'#course-notes':'.record-card').waitFor();if(route==='logic')await page.locator('#book-range').selectOption('1-2');for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.locator('#toast').evaluate(el=>el.hidden=true);await page.screenshot({path:`docs/screenshots-v2/${route}-${width}.png`,fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert(!overflow,route+' overflow at '+width);}}
  await page.goto(base+'/#ai');await page.locator('#course-notes').waitFor();
  for(const lessonId of ['project','compute','cnn','evaluation','linear','attention']){await page.locator('[data-lesson='+lessonId+']').first().click();await page.locator('#course-lab').click();for(const width of [390,320]){await page.setViewportSize({width,height:1000});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),lessonId+' tool overflow at '+width);await page.screenshot({path:`docs/screenshots-v2/tool-${lessonId}-${width}.png`,fullPage:true});}}
  const migrationContext=await browser.newContext(),migrationPage=await migrationContext.newPage();await migrationPage.goto(base);await migrationPage.evaluate(()=>{const legacy=StudyCore.initialState();legacy.experiences=[{id:'known-role',title:'学生工作记录',category:'学生工作',date:'',detail:'原贡献',evidence:'原证明位置'}];legacy.drafts='原申请草稿';localStorage.setItem('youyan.study.v1',JSON.stringify(legacy));});await migrationPage.reload();await migrationPage.goto(base+'/#materials');await migrationPage.locator('.record-card').waitFor();assert.match(await migrationPage.locator('.record-card').textContent(),/原证明位置/);await migrationPage.reload();await migrationPage.locator('.record-card').waitFor();assert.equal(await migrationPage.locator('.record-card').count(),1);assert.match(await migrationPage.locator('.legacy-draft').textContent(),/原申请草稿/);await migrationPage.evaluate(async()=>{await StudyVault.migrate([{id:'second',title:'新导入旧经历',category:'学习',date:'',detail:'',evidence:''}],true);});assert.equal(await migrationPage.evaluate(async()=> (await StudyVault.all('records')).length),2);await migrationContext.close();
  assert.deepEqual(errors,[]);console.log('V2 browser flows passed: actual Chinese PDF, structured mocked API, persistence, course tools, binary proofs, CSV escaping, full backup/restore, secret exclusion, XSS, 12 page layouts and 12 course-tool layouts.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
